from enum import Enum

class ResponseSignal(Enum):

    FILE_VALIDATION_SUCCESS = "FILE_VALIDATION_SUCCESS"
    FILE_SIZED_EXCEEDED = "FILE_SIZE_EXCEEDED"
    FILE_TYPE_NOT_SUPPORTED = "FILE_TYPE_NOT_SUPPORTED"
    FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS"
    FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"